FROM eclipse-temurin:22-jdk-jammy

# Directorio de trabajo dentro del contenedor
WORKDIR /app

# Copiamos el jar compilado al contenedor
COPY target/backend-0.0.1-SNAPSHOT.jar app.jar

# Exponemos el puerto de Spring Boot
EXPOSE 8080

# Comando para ejecutar la aplicación
ENTRYPOINT ["java", "-jar", "app.jar"]
